spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/urlshortener
    username: postgres
    password: Daliya8#r


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  base-url: http://localhost:8080
